[settings]
experimental = true
python_compile = false

[tools]
"go:github.com/charmbracelet/glow" = "latest"
"cargo:git-delta" = "latest"
go = "latest"
node = "23"
"npm:pnpm" = "latest"
fx = "latest"
"cargo:bandwhich" = "latest"
"cargo:mprocs" = "latest"
"cargo:rainfrog" = "latest"
deno = "latest"
"cargo:bat" = "latest"
uv = "latest"
"cargo:exa" = "latest"
pipx = "latest"
"cargo:du-dust" = "latest"
"cargo:ripgrep" = "latest"
fzf = "latest"
"cargo:yazi-fm" = "latest"
"cargo:yazi-cli" = "latest"
kind = "latest"
jq = "latest"
"cargo:difftastic" = "latest"
"cargo:mcfly" = "latest"
"cargo:https://github.com/bnprks/mcfly-fzf" = "branch:main"
"cargo:cargo-watch" = "latest"
usage = "latest"
"pipx:httpie" = "latest"
talhelper = "latest"
mc = "latest"
"cargo:viddy" = "latest"
"cargo:evcxr" = "latest"
"cargo:evcxr_repl" = "latest"
gitu = "latest"
"pipx:lrcup" = "latest"
bun = "latest"
viddy = "latest"
fd = "latest"
gitui = "latest"
gh = "latest"
kubectx = "latest"
dotnet = "9"
"cargo:broot" = "latest"
nim = "latest"
crystal = "latest"
air = "latest"
k9s = "latest"
ubi = "latest"
"ubi:carapace-sh/carapace-bin" = { version = "latest", exe = "carapace" }
zig = "latest"
spring-boot = "latest"
hurl = "latest"
syft = "latest"
grype = "latest"
"cargo:bob-nvim" = "latest"
