[settings]
experimental = true
python_compile = false
idiomatic_version_file_enable_tools = ["rust"]

[tools]
"go:github.com/charmbracelet/glow" = "latest"
"cargo:git-delta" = "latest"
go = "latest"
node = "24"
"npm:pnpm" = "latest"
fx = "latest"
"cargo:bandwhich" = "latest"
"cargo:mprocs" = "latest"
"cargo:rainfrog" = "latest"
deno = "latest"
"cargo:bat" = "latest"
uv = "latest"
"cargo:exa" = "latest"
pipx = "latest"
"cargo:du-dust" = "latest"
"cargo:ripgrep" = "latest"
fzf = "latest"
"cargo:yazi-fm" = "latest"
"cargo:yazi-cli" = "latest"
kind = "latest"
jq = "latest"
"cargo:difftastic" = "latest"
"cargo:cargo-watch" = "latest"
usage = "latest"
"pipx:httpie" = "latest"
talhelper = "latest"
mc = "2025-07-16T15-35-03Z"
"cargo:viddy" = "latest"
"cargo:evcxr" = "latest"
"cargo:evcxr_repl" = "latest"
"pipx:lrcup" = "latest"
bun = "latest"
viddy = "latest"
fd = "latest"
gh = "latest"
kubectx = "latest"
dotnet = "9"
"cargo:broot" = "latest"
nim = "latest"
crystal = "latest"
air = "latest"
k9s = "latest"
"ubi:carapace-sh/carapace-bin" = { version = "latest", exe = "carapace" }
spring-boot = "latest"
hurl = "latest"
syft = "latest"
grype = "latest"
"cargo:bob-nvim" = "latest"
"cargo:grcov" = "latest"
"ubi:git-bug/git-bug" = "latest"
eza = "latest"
"cargo:procs" = "latest"
lazygit = "latest"
"aqua:ipinfo/cli" = "latest"
"go:github.com/mahyarmirrashed/jdd" = "latest"
"aqua:gitui-org/gitui" = "latest"
"aqua:altsem/gitu" = "latest"
